### ISSUE TITLE
ESzabbix.py: AttributeError: 'module' object has no attribute 'PY2'

### ISSUE THREAD

**Issue by antonakv** [ejimz/Elasticsearch-zabbix#1]
Python script from this template doesn't work: 

Traceback (most recent call last): 
  File "./ESzabbix.py", line 5, in <module> 
    from pyes import \* 
  File "/usr/lib/python2.6/site-packages/pyes/**init**.py", line 26, in <module> 
    from .es import ES, file_to_attachment 
  File "/usr/lib/python2.6/site-packages/pyes/es.py", line 7, in <module> 
    if six.PY2: 
AttributeError: 'module' object has no attribute 'PY2'

**Comment by ejimz** [comment]
The code needs the "pyes" dependency
