### ISSUE TITLE
ImportError: cannot import name UnrewindableBodyError

### ISSUE THREAD

**Issue by qiangshui** [ejimz/Elasticsearch-zabbix#18]
[root@192.168.12.41 es]# python ESzabbix.py cluster status

Traceback (most recent call last):
  File "ESzabbix.py", line 6, in <module>
    from elasticsearch import *
  File "/usr/lib/python2.6/site-packages/elasticsearch/__init__.py", line 17, in                                                                                                                                                              <module>
    from .client import Elasticsearch
  File "/usr/lib/python2.6/site-packages/elasticsearch/client/__init__.py", line                                                                                                                                                              4, in <module>
    from ..transport import Transport
  File "/usr/lib/python2.6/site-packages/elasticsearch/transport.py", line 4, in                                                                                                                                                              <module>
    from .connection import Urllib3HttpConnection
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/__init__.py",                                                                                                                                                              line 3, in <module>
    from .http_urllib3 import Urllib3HttpConnection
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/http_urllib3.p                                                                                                                                                             y", line 2, in <module>
    import urllib3
  File "/usr/lib/python2.6/site-packages/urllib3/__init__.py", line 10, in <modu                                                                                                                                                             le>
    from .connectionpool import (
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 31, in                                                                                                                                                              <module>
    from .connection import (
  File "/usr/lib/python2.6/site-packages/urllib3/connection.py", line 45, in <mo                                                                                                                                                             dule>
    from .util.ssl_ import (
  File "/usr/lib/python2.6/site-packages/urllib3/util/__init__.py", line 4, in <                                                                                                                                                             module>
    from .request import make_headers
  File "/usr/lib/python2.6/site-packages/urllib3/util/request.py", line 5, in <m                                                                                                                                                             odule>
    from ..exceptions import UnrewindableBodyError
ImportError: cannot import name UnrewindableBodyError

can anyone help me please?

**Comment by qiangshui** [comment]
It seems that I aleardy installed urllib3 with pip which conflict with the python-urllib3.when I uninstall one of them,didn't get that error any more.

**Comment by qiangshui** [comment]
But there occured another problem:
[root@192.168.12.41 es]# python ESzabbix.py cluster status
```
No handlers could be found for logger "elasticsearch"
ZBX_NOTSUPPORTED
```

I found when run to line 63,the scripts didn't go on,

 ```
62         try:
63               returnval = conn.cluster.health()[unicode(sys.argv[2])]
64         except Exception, e:
65               zbx_fail()

so I add "print e" under the line 64,

62         try:
63               returnval = conn.cluster.health()[unicode(sys.argv[2])]
64         except Exception, e:
65               print e
66               zbx_fail()

```

Then run again,I got this:
[root@10-9-108-221 es]# python ESzabbix.py cluster status
```
No handlers could be found for logger "elasticsearch"
ConnectionError(('Connection aborted.', error(101, 'Network is unreachable'))) caused by: ProtocolError(('Connection aborted.', error(101, 'Network is unreachable')))
ZBX_NOTSUPPORTED
```
